apiVersion: v1
kind: Pod
metadata:
  name: hello-world-cpp
  namespace: softclient
spec:
  containers:
    - name: hello-world-cpp
      image: registry.dev.databricks.com/universe/hello-world-cpp
      imagePullPolicy: Always
      command: ["/bin/bash", "-c", "/usr/src/app/hello && tail -f /dev/null"]
      resources:
        limits:
          memory: "1720Mi"
          cpu: "4000m"
        requests:
          memory: "1720Mi"
          cpu: "4000m"
